on: [ push ]

name: build


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.78.0
          target: wasm32-unknown-unknown
          components: clippy
      - run: cargo clippy
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i -g wasm-pack
      - run: npm install
      - run: npm test --chrome
      - run: npm run build