on: [ push ]

name: build


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.78.0
          target: wasm32-unknown-unknown
          components: clippy
      - run: cargo clippy
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i -g wasm-pack
      - run: npm install
      - run: npm test
      - run: npm run build
        name: publish on netlify
      - uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}